version: '3.0'
services:
  gatsby:
    container_name: gatsby
    labels:
      keep: true
    build: ./docker
    volumes:
      - ./blog:/blog:delegated
      #      - ../docker/package.json:/blog/package.json
      - /blog/.cache
      - /blog/build
      - node_volumes:/blog/node_modules
      - /blog/public
    working_dir: /blog
    ports:
      - ${DEVELOP_EXTERNAL_PORT}:${DEVELOP_INTERNAL_PORT}
      - ${SERVE_EXTERNAL_PORT}:${SERVE_INTERNAL_PORT}
      - ${STATUS_EXTERNAL_PORT}:${STATUS_INTERNAL_PORT}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - CERT_NAME=${CERTS_FILE_NAME}
      - HTTPS_METHOD=noredirect
      - NODE_ENV=${NODE_ENV}
      - SITE_URL=${SITE_URL}
      - GOOGLE_ANALYTICS_TRACKING_ID=${GOOGLE_ANALYTICS_TRACKING_ID}
      - GOOGLE_ADSENSE_TRACKING_ID=${GOOGLE_ADSENSE_TRACKING_ID}
      - GOOGLE_ADSENSE_SLOT_SIDE_UPPER=${GOOGLE_ADSENSE_SLOT_SIDE_UPPER}
      - GOOGLE_ADSENSE_SLOT_SIDE_LOWER=${GOOGLE_ADSENSE_SLOT_SIDE_LOWER}
      - GOOGLE_ADSENSE_CONTENTS_LOWER=${GOOGLE_ADSENSE_CONTENTS_LOWER}
      - GOOGLE_ADSENSE_DRAWER=${GOOGLE_ADSENSE_DRAWER}
      - INTERNAL_STATUS_PORT=${STATUS_INTERNAL_PORT}
    stdin_open: true
    command: gatsby develop -p ${DEVELOP_INTERNAL_PORT} --host 0.0.0.0
    #command: yarn serve
    tty: true
volumes:
  node_volumes:
    name: gatsby_blog_node_volumes
    labels:
      keep: true
networks:
  default:
    name: ${NGINX_PROXY_NAME}

#networks:
#  default:
#    external: true
#    name: ${NET_WORK_NAME}
