version: '3.0'
services:
  gatsby:
    container_name: gatsby
    build: ./docker
    volumes:
      - ./blog:/blog:delegated
      #      - /blog/node_modules:/blog/node_modules
      - /blog/.cache
      #      - /blog/.vscode
      - /blog/build
      - /blog/node_modules
      - /blog/public
    working_dir: /blog
    ports:
      - ${DEVELOP_EXTERNAL_PORT}:${DEVELOP_INTERNAL_PORT}
      - ${SERVE_EXTERNAL_PORT}:${SERVE_INTERNAL_PORT}
      - ${STATUS_EXTERNAL_PORT}:${STATUS_INTERNAL_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - SITE_URL=${SITE_URL}
      - GOOGLE_ANALYTICS_TRACKING_ID=${GOOGLE_ANALYTICS_TRACKING_ID}
      - GOOGLE_ADSENSE_TRACKING_ID=${GOOGLE_ADSENSE_TRACKING_ID}
      - GOOGLE_ADSENSE_SLOT_SIDE_UPPER=${GOOGLE_ADSENSE_SLOT_SIDE_UPPER}
      - GOOGLE_ADSENSE_SLOT_SIDE_LOWER=${GOOGLE_ADSENSE_SLOT_SIDE_LOWER}
      - GOOGLE_ADSENSE_CONTENTS_LOWER=${GOOGLE_ADSENSE_CONTENTS_LOWER}
      - GOOGLE_ADSENSE_DRAWER=${GOOGLE_ADSENSE_DRAWER}
      - INTERNAL_STATUS_PORT=${STATUS_INTERNAL_PORT}
    stdin_open: true
    command: gatsby develop --host 0.0.0.0
    tty: true
networks:
  default:
    external:
      name: ${NET_WORK_NAME}
