name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install
        working-directory: blog

      - name: Run build
        env:
          SITE_URL: ${{secrets.SITE_URL}}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{secrets.GOOGLE_ANALYTICS_TRACKING_ID}}
          GOOGLE_ADSENSE_TRACKING_ID: ${{secrets.GOOGLE_ADSENSE_TRACKING_ID}}
          GOOGLE_ADSENSE_SLOT_SIDE_UPPER: ${{secrets.GOOGLE_ADSENSE_SLOT_SIDE_UPPER}}
          GOOGLE_ADSENSE_SLOT_SIDE_LOWER: ${{secrets.GOOGLE_ADSENSE_SLOT_SIDE_LOWER}}
          GOOGLE_ADSENSE_CONTENTS_LOWER: ${{secrets.GOOGLE_ADSENSE_CONTENTS_LOWER}}
        run: yarn build
        working-directory: blog

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: master

      - name: ls public Dir
        run: ls -la public
        working-directory: blog

